oakserver/oak

- request.ts
I wrote a simple middleware but couldn't get the request's headers. Maybe should add a method to get headers.
> add `Request.headers`

- request.ts
- request_test.ts
In [x-www-form-urlencoded][ref] request bodies, spaces are encoded as `+`. This replaces all `+` characters before instantiating `URLSearchParams`.
[ref]: https://en.wikipedia.org/wiki/Percent-encoding#The_application/x-www-form-urlencoded_type
> Replace + with space in form-urlencoded bodies

- README.md
The issue with serving static files using the snippet in the README.md file.
https://github.com/oakserver/oak/issues/69
> #Issue 69: Fix

- README.md
Change contextTypes to contentTypes on line 260 in README.md
> Fix contentTypes spelling in README.md

- application.ts
- application_test.ts
- keyStack_test.ts
- middleware_test.ts
- request_test.ts
- response_test.ts
- router_test.ts
- test_deps.ts
Use deps.ts consistently for dependencies.
After this change the only absolute URLs are found in deps.ts (of course) and in test code. Currently deps.ts seems to capture "production" dependencies pretty well, so I would propose adding a dev_deps.ts to capture the asserts from the test code. That change can be made separately but I'd love to hear your thoughts!
Edit: I just noticed test_deps.ts so I've updated the imports in the test code too. Seems like there's a split on which name to use! :)
> Use deps consistently

- response.ts
- response_test.ts
- util.ts
Fixes #119  
The koa framework uses this function to encode URI.
https://github.com/koajs/koa/blob/master/lib/response.js#L20
https://github.com/pillarjs/encodeurl/blob/master/index.js
> Fix encode uri on redirect

- README.md
I know this fix is extremely important, but nonetheless: one of the README examples uses "Conan Doyle, Author" instead of ".. Arthur".
That's all, thanks
> Fix Author name in README

- docs/index.md
Module version should be prefixed with `v`, for example this link returns 404 (https://deno.land/x/oak@4.0.0/mod.ts) but this links works fine (https://deno.land/x/oak@v4.0.0/mod.ts)
> Fix precise import typo

- application.ts
Currently, exporting the `app.handle` function must be exported with `bind(app)`:
```typescript
export default app.handle.bind(app);
```
With this change, the `app.handle` function may be exported directly as it will already be bound to the `app` instance:
```typescript
export default app.handle;
```
> Make `app.handle()` be an instance function

- request.ts
- `value` is the name of the key that'll contain the body data.
- {asReader: true} is the parameter to get the raw body, not just true.
Hi, hopefully I'm not out of line there. I just stumbled upon these errors (or at least I think they are errors) in the documentation, and rather than simply open an issue I thought I could fix it myself.
> Fix request.body documentation

- README.md
- body.ts
- body_test.ts
- docs/FAQ.md
- examples/echoServer.ts
- examples/routingServer.ts
- examples/staticServer.ts
- mod.ts
- request.ts
- request_test.ts
- test_deps.ts
This PR reworks `ctx.request.body()` in a breaking change way.
Previously, `.body()` returned a promise which resolved with an object containing the properties `type` and `value`.  Now, it simply returns the object with the properties `type` and `value`, and the type of the value of `value` will sometimes be a promise, or sometimes be another asynchronous type of object (`Deno.Reader` or `FormDataReader`), or `undefined` in the case where there is no body.
Also, the options have changed, to where previously there was an option flag `asReader` which when set to true returned a `"reader"` type body.  Now there is a `type` property which takes one of `"reader"`, `"form"`, `"form-data"`, `"json"`, `"raw"`, or `"text"`, and the body will be returned with that type.
> breaking: refactor ctx.request.body()

- .github/workflows/oak-ci.yml
BTW. We can add a scheduled task to test v1.x version regularly
> ci: upgrade deno action to v2

- application.ts
- application_test.ts
Addresses https://github.com/oakserver/oak/issues/206.
This PR amends the abort signal event handling to check against the `size` property of the `state.handling` `Set` rather than against the existence of the `Set` (which will always be truthy).
Updated existing signal test to use the created `AbortController`, and added a second test to cover the scenario where there are no requests in-flight to test this fix.
Changes:
* fix: ensure server closed on abort when no requests in flight
* test: fix current signal test
* test: add signal test for scenario with no requests in flight
> fix: ensure server closed on abort when no requests in flight

- deps.ts
- fixtures/.test.json
- fixtures/.test/test.json
- send.ts
- send_test.ts
- util.ts
- util_test.ts
It struck me as very slightly insecure to require `--allow-read=.` for `send` to work; in principle, a vulnerability in my code could expose secrets without requiring a further Deno exploit. This PR removes that requirement.
Before:
```
$ deno test --allow-read=./fixtures,$TEMP --allow-write=$TEMP
...
PermissionDenied: read access to <CWD>, run again with the --allow-read flag
...
test result: FAILED. 254 passed; 14 failed; 0 ignored; 0 measured; 0 filtered out (477ms)
```
After:
```
$ deno test --allow-read=./fixtures,$TEMP --allow-write=$TEMP
...
test result: ok. 275 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out (511ms)
```
```
project/
server.ts
secrets.ts
public/
index.html
...
$ deno run --allow-read=public server.ts
...
PermissionDenied: read access to <CWD>, run again …
```
> Do not require CWD permissions to serve static files; additional tests

- docs/index.md
The links to awsome-oak and middleware were broken. The should work now.
> fix links to other oakserver github projects

- .github/workflows/oak-ci.yml
- application.ts
- body.ts
- context.ts
- context_test.ts
- cookies.ts
- headers.ts
- helpers.ts
- httpError.ts
- middleware.ts
- middleware_test.ts
- request.ts
- request_test.ts
- response.ts
- router.ts
- send.ts
- server_sent_event.ts
- server_sent_event_test.ts
- util.ts
This fixes TS1371 that raises in deno 1.4.0 with the --unstable flag
Addresses #243
> Specify `import type` when applicable

- .github/workflows/oak-ci.yml
- application.ts
- deps.ts
- examples/closeServer.ts
- examples/cookieServer.ts
- examples/echoServer.ts
- examples/httpsServer.ts
- examples/readerServer.ts
- examples/routingServer.ts
- examples/server.ts
- examples/sseServer.ts
- examples/staticServer.ts
- request_test.ts
- test_deps.ts
Also moves to path_to_regexp (and updates to v6.3.0) on deno.land/x for better deduplication across modules.
> Update to Deno 1.4.4, std 0.73.0, media_types 2.5.1

- send.ts
- send_test.ts
It will check the `If-Modified-Since` request header, if the resource haven't been modified, then response with `304 Not Modified`.
> Add support for "If-Modified-Since" header in send()

- send.ts
- send_test.ts
This PR fix two problems in #266.
The condition of `304` was inverse... and it didn't handle a precision problem (the UTC string precision is 1 second or 1000 ms), which made the test false positive.
> Fix the checking of If-Modified-Since header

- application.ts
- application_test.ts
- context.ts
- http_server_native.ts
- http_server_std.ts
- mod.ts
- mod_test.ts
- server_sent_event.ts
- server_sent_event_test.ts
- types.d.ts
The enables server-sent events for the native HTTP bindings.
It requires denoland/deno#10197, which will be in Deno 1.9.1 (or canary release). (In Deno 1.9.0 it will cause a server to exit with an unhandled error when a client navigates away from the page)
> feat: enable server-sent events for native HTTP bindings

- multipart.ts
- multipart_test.ts
Resolves #335 
Fixes bug in mutipart with extra CRLF at the end of result files which in origin doesn't have newline at the end.
> Remove extra CRLF in multipart

- middleware/proxy.ts
- middleware/proxy_test.ts
> Fix: Retain search params of query url during proxying

- body.ts
- body_test.ts
In order to inspect a request's body before giving it to the proxy middleware, we need to consume it.
`proxy` uses `request.body({ type: "stream" })`, so we have to use the same method. All other methods are incompatible.
Still this means we read from the same underlying stream or Deno.Reader, which will fail.
This change returns a new independent reader, so the body can be read multiple times from various middleware that are unaware of each other.
> Allow streaming the request body multiple times

- httpError.ts
This PR fixes some minor issues I found while perusing the `httpError.ts` file.
The first commit delegates the assignment of the `HttpError#message` property to the `super` constructor of `Error`. This is so that the `message` is passed up to the prototype of `Error` rather than creating a whole new instance of `message` in `this` (`HttpError`).
Finally, the second commit simply removes a redundant usage of the ternary operator.
If there are any issues with these changes, please do inform me. I shall gladly resolve them and adjust the PR accordingly. Thanks!
> [chore] Small clean-up of logic in `HttpError` constructor

- .github/workflows/oak-ci.yml
- http_server_native.ts
- http_server_native_test.ts
- test_deps.ts
Fixes #314 
Recent comment prompted me to revisit this.
Having gone through the process of writing https://github.com/denoland/deno_std/pull/1128, now confident the root cause of the issue is that http connections are not closed when the underlying listener is closed - we need to track these connections and ensure that we close them off in order for the `httpConn.nextRequest()` to resolve (as `null`) otherwise it hangs forever.
This addition tracks each new `httpConn` to a set and then removes it again once / if the `httpConn` is closed again. We then update the server `close()` method to loop over the outstanding `httpConn`s in the set and close them.
Added test case that now passes following fixes.
> fix: ensure can close the native server by closing open http connections

- .github/workflows/oak-ci.yml
- application.ts
- body.ts
- context_test.ts
- deploy_test.ts
- http_server_native.ts
- middleware/proxy.ts
- send.ts
- util.ts
Previously, upgrading a connection would fail because of an incorrectly named attribute. Now it won't.
fix #370
> Fix upgrading connection to WebSocket

- testing.ts
- testing_test.ts
fix: https://github.com/oakserver/oak/issues/379
I found it inconvenient that the cookies property is not available in MockContext, so I made it possible to provide the cookies property. 
I've also added test cases for ctx.cookies.get() and ctx.cookies.set().
> fix: mocked contexts provide the cookies property

- README.md
I think it makes sense to use more modern syntax which suits the feel of Oak, and since Deno supports optional chaining from 1.0 😃
> Simplify code example

- testing.ts
- testing_test.ts
Previously, the following mocked test will fail to compile.
```typescript
import { testing } from 'oak';
import { assertEquals } from 'std/testing/assert.ts';
Deno.test({
name: 'should redirect user',
fn() {
const ctx = testing.createMockContext();
ctx.response.redirect('/hello/world');
assertEquals(ctx.response.headers.get('Location'), '/hello/world');
},
});
```
A seemingly irrelevant error message will report that the failure is due to the fact that "`this.#request.accepts` is `undefined`". This is because the `Response#redirect` implementation internally invokes the `Request#accepts` method (as seen below).
https://github.com/oakserver/oak/blob/b85ffc3d48af6b0d6c3b3a37aa5142dbc068cffd/response.ts#L255-L260
However, prior to this PR, the mocked `Request` did not implement the `accepts` …
> Fix(testing): implement mock for `Request#accepts`

- structured_clone.ts
This will fix this dnt issue:
```ts
npm/src/structured_clone.ts:149:28 - error TS2339: Property 'core' does not exist on type 'typeof Deno'.
149 const core = dntShim.Deno?.core;
~~~~
```
Getting dnt to understand global scope augmentation will be a challenge... I'm not sure how it will do it with shimming, but hopefully the occurrences of this will be rare so people can work around it.
> fix: use interface to represent `Deno.core` instead of modifying global type scope

- README.md
This PR updates the README to represent changes for #442 made in commit ad6b896e3621c26b226fa92d8f2dee5bcc8a5631:
- Docs for `accepts` were adjusted slightly
- Docs for `acceptsEncodings` were adjusted slightly
- Docs for `acceptsLanguages` were adjusted slightly
- Docs for `acceptsCharsets` were removed, because the function was marked as deprecated.
_(I couldn't find docs for another deprecated function, so I was not sure if marking the function as deprecated or removing it entirely is preferred)_
> docs: Update README to represent changes made in ad6b896 (#442)

- README.md
This method is (now) async as it turns out.
> README: Added `await` to etag.calculate

- .github/workflows/oak-ci.yml
v1 is deprecated now
https://github.com/codecov/codecov-action#%EF%B8%8F--deprecration-of-v1
> update codecov action

- deno.jsonc
- http_server_native.ts
- http_server_native_test.ts
- http_server_native_unstable_test.ts
- http_server_node_test.ts
- test_deps.ts
Fixes #528 
No longer waits for a request on a connection to be fully responded to and resolved before picking up the next request, ensuring to handle errors as previously.
Added a couple of tests - one for the error handling, and another to assert on the ability to handle multiple requests on a connection in parallel without blocking.
> fix: don't block subsequent requests on a connection

- multipart.ts
'og the form data file' 🠚 'of the form data file'. Simple stuff.
> Fix typo in `multipart.ts`

- mod.ts
- mod_test.ts
Expose `createHttpError` so it can be used for error handling on apps.
> fix: expose createHttpError

- util.ts
The keyFile and certFile options are marked as "deprecated" in deno.d.ts.
```typescript
app.listen({ port: 443, secure: true, key: "...", cert: "..." })
```
> fix Deno.ListenTlsOptions detection

- README.md
There's an `await` missing in the Static Content exmple of the Readme. This was causing the dreaded "The response is not writable." error in my case.
> Add missing await in Readme.md Static Content example.

- README.md
- router.ts
- router_test.ts
This allows overriding the parameter types in a router method by defininig just
one generic type parameter.
Resolves #433.
- Allow only giving path parameter types to a router method
- Add documenation for overriding parameter types
> Make overriding router parameter types easier

- multipart.ts
added unit (bytes) (The wording *"the default is 10MB"* made me unsure whether the unit is bytes or MB.)
and a crossref from `maxFileSize` to `maxSize` (I went into a rabbit-hole of in-memory filesystems before learning about that option. 😅)
> multipart.ts: docs: tweak maxSize and maxFileSize

- router.ts
- router_test.ts
Thank you for merging my previous PR.
Unfortunately I now noticed, that there where some missing generic parameters, that I simply copied over last time (or rather did not copy, because they weren't there :-D)
They cause the `router.all` and `router.patch` methods to not be usable with explicit route parameters and application state.
I have added a test for this specific case and inserted the missing generic parameters.
For the other methods they were already used like this, so I think this was the original intention.
> fix(router): add missing generic parameters for multiple middlewares

- router.ts
Route name, if provided, is not preserved during route matching, correspondingly making middleware unable to access it via the router context
> fix: save route name during route matching

- application.ts
- examples/countingServer.ts
- middleware.ts
- middleware_test.ts
- mod.ts
This extends Middleware to allow objects to be used, making it similar to event targets.
It allows an optional `init` method that will be invoked when `listen` is called.
Objects will be useful for encapsulating larger amounts of logic or state, or when delayed initialization is desired such as a database driver.
> feat: add MiddlewareObject

- application.ts
This may have been missed in db116d1c43f858fe3ba5027140556a7ccd0feaf8
> fix: wrong file dynamically imported

- http_server_native.test.ts
- http_server_native.ts
Hello,
I recently discovered an issue when using Superoak and Oak v13.
It seems that the refactory performed to replace `Deno.serveHttp` with `Deno.server` caused the close method within the oak native http throw `Bad Resource ID` when the controller dispatched an abort event.
```
error: BadResource: Bad resource ID
controller.abort();
^
at AbortSignal.CallbackContext.signal.addEventListener.once (ext:deno_http/00_serve.js:355:9)
at innerInvokeEventListeners (ext:deno_web/02_event.js:754:7)
at invokeEventListeners (ext:deno_web/02_event.js:801:5)
at dispatch (ext:deno_web/02_event.js:658:9)
at AbortSignal.dispatchEvent (ext:deno_web/02_event.js:1043:12)
at AbortSignal.[[[signalAbort]]] (ext:deno_web/03_abort_signal.js:146:11)
at AbortController.abort …
```
> fix: http_server_native when closing with signal abort event

- .github/workflows/ci.yml
This PR enables Deno canary in CI, which currently is the same as enabling Deno 2.0.0-rc.0. This has the obvious benefit of future-proofing this package for Deno 2, but also gives us (Deno) early insight into any issues that users may run into when migrating from Deno 1 to 2.
> chore: run CI on canary

- body.test.ts
- body.ts
- middleware/proxy.test.ts
- middleware/proxy.ts
- testing.ts
When the body is consumed, it is still available in the `#memo` private property. All the possible types there are a match for `BodyInit`. So there is nothing preventing us from using it directly in the `proxy` middleware.
Resolves #642
> Allow proxy middleware to reuse body from memo

- deps.ts
There is a vulnerability that is fixed by this update:
> path-to-regexp  4.0.0 - 6.2.2
> Severity: high
> path-to-regexp outputs backtracking regular expressions - https://github.com/advisories/GHSA-9wv6-86v2-598j
> Update vulnerable path-to-regexp version
