- response.ts
> Fix typo in header name

- router.ts
- router_test.ts
There's a `prefix` option but never apply, this pr fixes that.
> fix router prefix

- .travis.yml
- deps.ts
- examples/echoServer.ts
- examples/routingServer.ts
- examples/server.ts
- examples/staticServer.ts
- test_deps.ts
> Bump to deno  v0.24.0

- .travis.yml
- README.md
- deps.ts
- examples/echoServer.ts
- examples/routingServer.ts
- examples/server.ts
- examples/staticServer.ts
- request.ts
- request_test.ts
- test_deps.ts
See denoland/deno#3575 for details of std/http API upgrade.
> Bump Deno 0.28.1 and update request.body()

- README.md
TypeScript compiler error in Router example in read me
> doc: fix typescript error in router example

- README.md
Ref https://doc.deno.land/about#badges
> Added deno doc badge

- application.ts
> Resolving Request Deadlocks

- application_test.ts
- context.ts
- cookieHandler.ts
- cookieHandler_test.ts
- deps.ts
#46
Based on https://deno.land/std/http/cookie.ts
```ts
app.use((ctx) => {
ctx.cookies.get('foo'); //=> "bar"
ctx.cookies.set({
name: 'foo',
value: 'bar',
httpOnly: true
});
ctx.cookies.del('foo');
});
```
> An easy cookie handler

- router.ts
- router_test.ts
There's a defined strict option in Router but never apply.
This PR makes it strict option configurable by arguments.
> Make strict option configurable

- request.ts
Snuck in with the following commit: https://github.com/oakserver/oak/commit/a380e1242422ca24f9d62565e3f59fc18e3a49c5
> Remove superfluous console.log

- application.ts
- context_test.ts
- deps.ts
- examples/static/index.html
- response.ts
- send.ts
- send_test.ts
Allows files to be sent without needing to read the full file into memory.
> Use Deno.File with send()

- application.ts
- application_test.ts
- context.ts
- context_test.ts
- deps.ts
- send.ts
- test_deps.ts
Fixes #105 
@katywings if you could take a look and see if what I did makes sense.
> Add context.upgrade() to handle WebSockets

- README.md
- context.ts
- context_test.ts
- deps.ts
- docs/index.md
- docs/sse.md
- examples/resources/sseServer_index.html
- examples/sseServer.ts
- mod.ts
- mod_test.ts
- server_sent_event.ts
- server_sent_event_test.ts
- test_deps.ts
> Add support for server-sent events

- .github/workflows/oak-ci.yml
- headers.ts
- multipart.ts
> CI(improve): add format check

- README.md
- body.ts
- body_test.ts
- docs/FAQ.md
- examples/echoServer.ts
- examples/routingServer.ts
- examples/staticServer.ts
- mod.ts
- request.ts
- request_test.ts
- test_deps.ts
> breaking: Refactor ctx.request.body() (#192)

- .github/workflows/oak-ci.yml
- response.ts
Update the CI version to run as Deno v1.3.0
> Update CI version to Deno v1.3.0

- cookies.ts
Fixes cookie `maxAge` issue #236
> Fixes #236

- README.md
The type `"raw"` was renamed to `"bytes"`, `"stream"` is a new type and `"form-data"` was not documented completely.
> Update request body types documentation in readme

- README.md
This PR will fix #214 by improving the docs for serving static content.
> docs: Improve static content (Fixes #214)

- headers_test.ts
Add test case of headers - readHeaders()
> test(headers): add malformed, invalidHeaderKey, unexpectedEnd fixture

- examples/httpsServer.ts
Following #636 , https server example update.
> chore: update https server example

- application.ts
- middleware/etag.test.ts
- router.test.ts
- send.test.ts
- testing.ts
use PropertyKey instaed of key list
> refactor: use PropertyKey instaed of key list
